import type { PricingTier } from "@/types";

export const pricingTiers: PricingTier[] = [
  {
    name: "Starter",
    description: "Para testar o mercado público sem custo.",
    price: "R$ 0",
    period: "para sempre",
    features: [
      "Busca de editais com filtros básicos",
      "Até 5 alertas personalizados",
      "Visualização de editais",
      "Histórico dos últimos 30 dias",
      "Suporte via central de ajuda",
    ],
    cta: "Criar conta grátis",
    ctaMicro: "Sem cartão de crédito",
    highlighted: false,
  },
  {
    name: "Profissional",
    description: "Para empresas que participam ativamente de pregões.",
    price: "R$ 149",
    period: "por mês",
    features: [
      "Alertas ilimitados",
      "Análise completa de editais",
      "Gestão de propostas e documentos",
      "Relatórios de desempenho",
      "Histórico completo",
      "Suporte prioritário",
      "API de integração",
    ],
    cta: "Começar teste grátis",
    ctaMicro: "14 dias grátis, cancele antes sem cobrança",
    highlighted: true,
  },
  {
    name: "Enterprise",
    description: "Para grupos e consultorias com alto volume de propostas.",
    price: "Sob consulta",
    period: "personalizado para sua equipe",
    features: [
      "Tudo do Profissional",
      "Gerente de conta dedicado",
      "Integrações com ERP e sistemas internos",
      "SLA de atendimento",
      "Usuários ilimitados",
      "Treinamento da equipe",
      "Análise de concorrência avançada",
    ],
    cta: "Falar com vendas",
    ctaMicro: "Resposta em até 1 dia útil",
    highlighted: false,
  },
];
